### ISSUE TITLE
REST API coverage tracking

### ISSUE THREAD

**Issue by benpueschel** [benpueschel/teatime#1]
# REST API coverage tracking

This is a meta-issue to document the API coverage of all REST routes:

## Search

- [x] GET `/users/search`
- [ ] GET `/admin/emails/search`
- [ ] GET `/orgs/{org}/teams/search`
- [x] GET `/repos/issues/search`
- [x] GET `/repos/search`
- [ ] GET `/topics/search`

## Users

- [x] GET `/user`
- [ ] GET `/user/actions/runners/registration-token`
- [ ] DELETE `/user/actions/secrets/{secretname}`
- [ ] PUT `/user/actions/secrets/{secretname}`
- [ ] GET `/user/actions/variables`
- [ ] DELETE `/user/actions/variables/{variablename}`
- [ ] GET `/user/actions/variables/{variablename}`
- [ ] POST `/user/actions/variables/{variablename}`
- [ ] PUT `/user/actions/variables/{variablename}`
- [ ] GET `/user/applications/oauth2`
- [ ] POST `/user/applications/oauth2`
- [ ] DELETE `/user/applications/oauth2/{id}`
- [ ] GET `/user/applications/oauth2/{id}`
- [ ] PATCH `/user/applications/oauth2/{id}`
- [ ] DELETE `/user/avatar`
- [ ] POST `/user/avatar`
- [ ] GET `/user/blocks`
- [ ] DELETE `/user/blocks/{username}`
- [ ] GET `/user/blocks/{username}`
- [ ] PUT `/user/blocks/{username}`
- [ ] DELETE `/user/emails`
- [ ] GET `/user/emails`
- [ ] POST `/user/emails`
- [ ] GET `/user/followers`
- [ ] GET `/user/following`
- [ ] DELETE `/user/following/{username}`
- [ ] GET `/user/following/{username}`
- [ ] PUT `/user/following/{username}`
- [ ] GET `/user/gpg_key_token`
- [ ] POST `/user/gpg_key_verify`
- [ ] GET `/user/gpg_keys`
- [ ] POST `/user/gpg_keys`
- [ ] DELETE `/user/gpg_keys/{id}`
- [ ] GET `/user/gpg_keys/{id}`
- [ ] GET `/user/hooks`
- [ ] POST `/user/hooks`
- [ ] DELETE `/user/hooks/{id}`
- [ ] GET `/user/hooks/{id}`
- [ ] PATCH `/user/hooks/{id}`
- [ ] GET `/user/keys`
- [ ] POST `/user/keys`
- [ ] DELETE `/user/keys/{id}`
- [ ] GET `/user/keys/{id}`
- [x] GET `/user/orgs`
- [x] GET `/user/repos`
- [x] POST `/user/repos`
- [x] GET `/user/settings`
- [x] PATCH `/user/settings`
- [x] GET `/user/starred`
- [x] DELETE `/user/starred/{owner}/{repo}`
- [x] GET `/user/starred/{owner}/{repo}`
- [x] PUT `/user/starred/{owner}/{repo}`
- [ ] GET `/user/stopwatches`
- [ ] GET `/user/subscriptions`
- [ ] GET `/user/teams`
- [ ] GET `/user/times`
- [x] GET `/users/{username}`
- [ ] GET `/users/{username}/activities/feeds`
- [ ] GET `/users/{username}/followers`
- [ ] GET `/users/{username}/following`
- [ ] GET `/users/{username}/following/{target}`
- [ ] GET `/users/{username}/gpg_keys`
- [ ] GET `/users/{username}/heatmap`
- [ ] GET `/users/{username}/keys`
- [ ] GET `/users/{username}/orgs`
- [ ] GET `/users/{username}/orgs/{org}/permissions`
- [x] GET `/users/{username}/repos`
- [x] GET `/users/{username}/starred`
- [ ] GET `/users/{username}/subscriptions`
- [x] GET `/users/{username}/tokens`
- [x] POST `/users/{username}/tokens`
- [x] DELETE `/users/{username}/tokens/{token}`

## Repositories

- [x] POST `/repos/migrate`
- [x] DELETE `/repos/{owner}/{repo}`
- [x] GET `/repos/{owner}/{repo}`
- [x] PATCH `/repos/{owner}/{repo}`
- [ ] GET `/repos/{owner}/{repo}/actions/runners/registration-token`
- [ ] GET `/repos/{owner}/{repo}/actions/secrets`
- [ ] DELETE `/repos/{owner}/{repo}/actions/secrets/{secretname}`
- [ ] PUT `/repos/{owner}/{repo}/actions/secrets/{secretname}`
- [ ] GET `/repos/{owner}/{repo}/actions/tasks`
- [ ] GET `/repos/{owner}/{repo}/actions/variables`
- [ ] DELETE `/repos/{owner}/{repo}/actions/variables/{variablename}`
- [ ] GET `/repos/{owner}/{repo}/actions/variables/{variablename}`
- [ ] POST `/repos/{owner}/{repo}/actions/variables/{variablename}`
- [ ] PUT `/repos/{owner}/{repo}/actions/variables/{variablename}`
- [ ] GET `/repos/{owner}/{repo}/activities/feeds`
- [ ] GET `/repos/{owner}/{repo}/archive/{archive}`
- [ ] GET `/repos/{owner}/{repo}/assignees`
- [ ] DELETE `/repos/{owner}/{repo}/avatar`
- [ ] POST `/repos/{owner}/{repo}/avatar`
- [ ] GET `/repos/{owner}/{repo}/branch_protections`
- [ ] POST `/repos/{owner}/{repo}/branch_protections`
- [ ] DELETE `/repos/{owner}/{repo}/branch_protections/{name}`
- [ ] GET `/repos/{owner}/{repo}/branch_protections/{name}`
- [ ] PATCH `/repos/{owner}/{repo}/branch_protections/{name}`
- [x] GET `/repos/{owner}/{repo}/branches`
- [x] POST `/repos/{owner}/{repo}/branches`
- [x] DELETE `/repos/{owner}/{repo}/branches/{branch}`
- [x] GET `/repos/{owner}/{repo}/branches/{branch}`
- [ ] GET `/repos/{owner}/{repo}/collaborators`
- [ ] DELETE `/repos/{owner}/{repo}/collaborators/{collaborator}`
- [ ] GET `/repos/{owner}/{repo}/collaborators/{collaborator}`
- [ ] PUT `/repos/{owner}/{repo}/collaborators/{collaborator}`
- [ ] GET `/repos/{owner}/{repo}/collaborators/{collaborator}/permission`
- [x] GET `/repos/{owner}/{repo}/commits`
- [ ] GET `/repos/{owner}/{repo}/commits/{ref}/status`
- [ ] GET `/repos/{owner}/{repo}/commits/{ref}/statuses`
- [ ] GET `/repos/{owner}/{repo}/commits/{sha}/pull`
- [ ] GET `/repos/{owner}/{repo}/compare/{basehead}`
- [x] GET `/repos/{owner}/{repo}/contents`
- [ ] POST `/repos/{owner}/{repo}/contents`
- [x] DELETE `/repos/{owner}/{repo}/contents/{filepath}`
- [x] GET `/repos/{owner}/{repo}/contents/{filepath}`
- [x] POST `/repos/{owner}/{repo}/contents/{filepath}`
- [x] PUT `/repos/{owner}/{repo}/contents/{filepath}`
- [ ] POST `/repos/{owner}/{repo}/diffpatch`
- [ ] GET `/repos/{owner}/{repo}/editorconfig/{filepath}`
- [x] GET `/repos/{owner}/{repo}/forks`
- [x] POST `/repos/{owner}/{repo}/forks`
- [ ] GET `/repos/{owner}/{repo}/git/blobs/{sha}`
- [ ] GET `/repos/{owner}/{repo}/git/commits/{sha}`
- [ ] GET `/repos/{owner}/{repo}/git/commits/{sha}.{diffType}`
- [ ] GET `/repos/{owner}/{repo}/git/notes/{sha}`
- [ ] GET `/repos/{owner}/{repo}/git/refs`
- [ ] GET `/repos/{owner}/{repo}/git/refs/{ref}`
- [ ] GET `/repos/{owner}/{repo}/git/tags/{sha}`
- [ ] GET `/repos/{owner}/{repo}/git/trees/{sha}`
- [ ] GET `/repos/{owner}/{repo}/hooks`
- [ ] POST `/repos/{owner}/{repo}/hooks`
- [ ] GET `/repos/{owner}/{repo}/hooks/git`
- [ ] DELETE `/repos/{owner}/{repo}/hooks/git/{id}`
- [ ] GET `/repos/{owner}/{repo}/hooks/git/{id}`
- [ ] PATCH `/repos/{owner}/{repo}/hooks/git/{id}`
- [ ] DELETE `/repos/{owner}/{repo}/hooks/{id}`
- [ ] GET `/repos/{owner}/{repo}/hooks/{id}`
- [ ] PATCH `/repos/{owner}/{repo}/hooks/{id}`
- [ ] POST `/repos/{owner}/{repo}/hooks/{id}/tests`
- [ ] GET `/repos/{owner}/{repo}/issue_config`
- [ ] GET `/repos/{owner}/{repo}/issue_config/validate`
- [ ] GET `/repos/{owner}/{repo}/issue_templates`
- [ ] GET `/repos/{owner}/{repo}/keys`
- [ ] POST `/repos/{owner}/{repo}/keys`
- [ ] DELETE `/repos/{owner}/{repo}/keys/{id}`
- [ ] GET `/repos/{owner}/{repo}/keys/{id}`
- [ ] GET `/repos/{owner}/{repo}/labels`
- [ ] POST `/repos/{owner}/{repo}/labels`
- [ ] DELETE `/repos/{owner}/{repo}/labels/{id}`
- [ ] GET `/repos/{owner}/{repo}/labels/{id}`
- [ ] PATCH `/repos/{owner}/{repo}/labels/{id}`
- [ ] GET `/repos/{owner}/{repo}/languages`
- [ ] GET `/repos/{owner}/{repo}/media/{filepath}`
- [ ] GET `/repos/{owner}/{repo}/milestones`
- [ ] POST `/repos/{owner}/{repo}/milestones`
- [ ] DELETE `/repos/{owner}/{repo}/milestones/{id}`
- [ ] GET `/repos/{owner}/{repo}/milestones/{id}`
- [ ] PATCH `/repos/{owner}/{repo}/milestones/{id}`
- [ ] POST `/repos/{owner}/{repo}/mirror-sync`
- [ ] GET `/repos/{owner}/{repo}/new_pin_allowed`
- [ ] GET `/repos/{owner}/{repo}/notifications`
- [ ] PUT `/repos/{owner}/{repo}/notifications`
- [x] GET `/repos/{owner}/{repo}/pulls`
- [x] POST `/repos/{owner}/{repo}/pulls`
- [x] GET `/repos/{owner}/{repo}/pulls/pinned`
- [x] GET `/repos/{owner}/{repo}/pulls/{base}/{head}`
- [x] GET `/repos/{owner}/{repo}/pulls/{index}`
- [x] PATCH `/repos/{owner}/{repo}/pulls/{index}`
- [ ] GET `/repos/{owner}/{repo}/pulls/{index}.{diffType}`
- [ ] GET `/repos/{owner}/{repo}/pulls/{index}/commits`
- [ ] GET `/repos/{owner}/{repo}/pulls/{index}/files`
- [ ] DELETE `/repos/{owner}/{repo}/pulls/{index}/merge`
- [ ] GET `/repos/{owner}/{repo}/pulls/{index}/merge`
- [ ] POST `/repos/{owner}/{repo}/pulls/{index}/merge`
- [ ] DELETE `/repos/{owner}/{repo}/pulls/{index}/requested_reviewers`
- [ ] POST `/repos/{owner}/{repo}/pulls/{index}/requested_reviewers`
- [x] GET `/repos/{owner}/{repo}/pulls/{index}/reviews`
- [ ] POST `/repos/{owner}/{repo}/pulls/{index}/reviews`
- [ ] DELETE `/repos/{owner}/{repo}/pulls/{index}/reviews/{id}`
- [ ] GET `/repos/{owner}/{repo}/pulls/{index}/reviews/{id}`
- [ ] POST `/repos/{owner}/{repo}/pulls/{index}/reviews/{id}`
- [ ] GET `/repos/{owner}/{repo}/pulls/{index}/reviews/{id}/comments`
- [ ] POST `/repos/{owner}/{repo}/pulls/{index}/reviews/{id}/dismissals`
- [ ] POST `/repos/{owner}/{repo}/pulls/{index}/reviews/{id}/undismissals`
- [ ] POST `/repos/{owner}/{repo}/pulls/{index}/update`
- [ ] GET `/repos/{owner}/{repo}/push_mirrors`
- [ ] POST `/repos/{owner}/{repo}/push_mirrors`
- [ ] POST `/repos/{owner}/{repo}/push_mirrors-sync`
- [ ] DELETE `/repos/{owner}/{repo}/push_mirrors/{name}`
- [ ] GET `/repos/{owner}/{repo}/push_mirrors/{name}`
- [ ] GET `/repos/{owner}/{repo}/raw/{filepath}`
- [ ] GET `/repos/{owner}/{repo}/releases`
- [ ] POST `/repos/{owner}/{repo}/releases`
- [ ] GET `/repos/{owner}/{repo}/releases/latest`
- [ ] DELETE `/repos/{owner}/{repo}/releases/tags/{tag}`
- [ ] GET `/repos/{owner}/{repo}/releases/tags/{tag}`
- [ ] DELETE `/repos/{owner}/{repo}/releases/{id}`
- [ ] GET `/repos/{owner}/{repo}/releases/{id}`
- [ ] PATCH `/repos/{owner}/{repo}/releases/{id}`
- [ ] GET `/repos/{owner}/{repo}/releases/{id}/assets`
- [ ] POST `/repos/{owner}/{repo}/releases/{id}/assets`
- [ ] DELETE `/repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}`
- [ ] GET `/repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}`
- [ ] PATCH `/repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}`
- [ ] GET `/repos/{owner}/{repo}/reviewers`
- [ ] GET `/repos/{owner}/{repo}/signing-key.gpg`
- [ ] GET `/repos/{owner}/{repo}/stargazers`
- [ ] GET `/repos/{owner}/{repo}/statuses/{sha}`
- [ ] POST `/repos/{owner}/{repo}/statuses/{sha}`
- [ ] GET `/repos/{owner}/{repo}/subscribers`
- [ ] DELETE `/repos/{owner}/{repo}/subscription`
- [ ] GET `/repos/{owner}/{repo}/subscription`
- [ ] PUT `/repos/{owner}/{repo}/subscription`
- [ ] GET `/repos/{owner}/{repo}/tag_protections`
- [ ] POST `/repos/{owner}/{repo}/tag_protections`
- [ ] DELETE `/repos/{owner}/{repo}/tag_protections/{id}`
- [ ] GET `/repos/{owner}/{repo}/tag_protections/{id}`
- [ ] PATCH `/repos/{owner}/{repo}/tag_protections/{id}`
- [ ] GET `/repos/{owner}/{repo}/tags`
- [ ] POST `/repos/{owner}/{repo}/tags`
- [ ] DELETE `/repos/{owner}/{repo}/tags/{tag}`
- [ ] GET `/repos/{owner}/{repo}/tags/{tag}`
- [ ] GET `/repos/{owner}/{repo}/teams`
- [ ] DELETE `/repos/{owner}/{repo}/teams/{team}`
- [ ] GET `/repos/{owner}/{repo}/teams/{team}`
- [ ] PUT `/repos/{owner}/{repo}/teams/{team}`
- [ ] GET `/repos/{owner}/{repo}/times`
- [ ] GET `/repos/{owner}/{repo}/times/{user}`
- [ ] GET `/repos/{owner}/{repo}/topics`
- [ ] PUT `/repos/{owner}/{repo}/topics`
- [ ] DELETE `/repos/{owner}/{repo}/topics/{topic}`
- [ ] PUT `/repos/{owner}/{repo}/topics/{topic}`
- [ ] POST `/repos/{owner}/{repo}/transfer`
- [ ] POST `/repos/{owner}/{repo}/transfer/accept`
- [ ] POST `/repos/{owner}/{repo}/transfer/reject`
- [ ] POST `/repos/{owner}/{repo}/wiki/new`
- [ ] DELETE `/repos/{owner}/{repo}/wiki/page/{pageName}`
- [ ] GET `/repos/{owner}/{repo}/wiki/page/{pageName}`
- [ ] PATCH `/repos/{owner}/{repo}/wiki/page/{pageName}`
- [ ] GET `/repos/{owner}/{repo}/wiki/pages`
- [ ] GET `/repos/{owner}/{repo}/wiki/revisions/{pageName}`
- [x] POST `/repos/{template_owner}/{template_repo}/generate`
- [ ] GET `/repositories/{id}`

## Issues

- [x] GET `/repos/{owner}/{repo}/issues`
- [x] POST `/repos/{owner}/{repo}/issues`
- [x] GET `/repos/{owner}/{repo}/issues/comments`
- [x] DELETE `/repos/{owner}/{repo}/issues/comments/{id}`
- [ ] GET `/repos/{owner}/{repo}/issues/comments/{id}`
- [x] PATCH `/repos/{owner}/{repo}/issues/comments/{id}`
- [ ] GET `/repos/{owner}/{repo}/issues/comments/{id}/assets`
- [ ] POST `/repos/{owner}/{repo}/issues/comments/{id}/assets`
- [ ] DELETE `/repos/{owner}/{repo}/issues/comments/{id}/assets/{attachment_id}`
- [ ] GET `/repos/{owner}/{repo}/issues/comments/{id}/assets/{attachment_id}`
- [ ] PATCH `/repos/{owner}/{repo}/issues/comments/{id}/assets/{attachment_id}`
- [ ] DELETE `/repos/{owner}/{repo}/issues/comments/{id}/reactions`
- [ ] GET `/repos/{owner}/{repo}/issues/comments/{id}/reactions`
- [ ] POST `/repos/{owner}/{repo}/issues/comments/{id}/reactions`
- [ ] GET `/repos/{owner}/{repo}/issues/pinned`
- [x] DELETE `/repos/{owner}/{repo}/issues/{index}`
- [x] GET `/repos/{owner}/{repo}/issues/{index}`
- [x] PATCH `/repos/{owner}/{repo}/issues/{index}`
- [ ] GET `/repos/{owner}/{repo}/issues/{index}/assets`
- [ ] POST `/repos/{owner}/{repo}/issues/{index}/assets`
- [ ] DELETE `/repos/{owner}/{repo}/issues/{index}/assets/{attachment_id}`
- [ ] GET `/repos/{owner}/{repo}/issues/{index}/assets/{attachment_id}`
- [ ] PATCH `/repos/{owner}/{repo}/issues/{index}/assets/{attachment_id}`
- [ ] DELETE `/repos/{owner}/{repo}/issues/{index}/blocks`
- [ ] GET `/repos/{owner}/{repo}/issues/{index}/blocks`
- [ ] POST `/repos/{owner}/{repo}/issues/{index}/blocks`
- [ ] GET `/repos/{owner}/{repo}/issues/{index}/comments`
- [ ] POST `/repos/{owner}/{repo}/issues/{index}/comments`
- [ ] DELETE `/repos/{owner}/{repo}/issues/{index}/comments/{id}`
- [ ] PATCH `/repos/{owner}/{repo}/issues/{index}/comments/{id}`
- [ ] POST `/repos/{owner}/{repo}/issues/{index}/deadline`
- [ ] DELETE `/repos/{owner}/{repo}/issues/{index}/dependencies`
- [ ] GET `/repos/{owner}/{repo}/issues/{index}/dependencies`
- [ ] POST `/repos/{owner}/{repo}/issues/{index}/dependencies`
- [ ] DELETE `/repos/{owner}/{repo}/issues/{index}/labels`
- [ ] GET `/repos/{owner}/{repo}/issues/{index}/labels`
- [ ] POST `/repos/{owner}/{repo}/issues/{index}/labels`
- [ ] PUT `/repos/{owner}/{repo}/issues/{index}/labels`
- [ ] DELETE `/repos/{owner}/{repo}/issues/{index}/labels/{id}`
- [ ] DELETE `/repos/{owner}/{repo}/issues/{index}/pin`
- [ ] POST `/repos/{owner}/{repo}/issues/{index}/pin`
- [ ] PATCH `/repos/{owner}/{repo}/issues/{index}/pin/{position}`
- [ ] DELETE `/repos/{owner}/{repo}/issues/{index}/reactions`
- [ ] GET `/repos/{owner}/{repo}/issues/{index}/reactions`
- [ ] POST `/repos/{owner}/{repo}/issues/{index}/reactions`
- [ ] DELETE `/repos/{owner}/{repo}/issues/{index}/stopwatch/delete`
- [ ] POST `/repos/{owner}/{repo}/issues/{index}/stopwatch/start`
- [ ] POST `/repos/{owner}/{repo}/issues/{index}/stopwatch/stop`
- [ ] GET `/repos/{owner}/{repo}/issues/{index}/subscriptions`
- [ ] GET `/repos/{owner}/{repo}/issues/{index}/subscriptions/check`
- [ ] DELETE `/repos/{owner}/{repo}/issues/{index}/subscriptions/{user}`
- [ ] PUT `/repos/{owner}/{repo}/issues/{index}/subscriptions/{user}`
- [ ] GET `/repos/{owner}/{repo}/issues/{index}/timeline`
- [ ] DELETE `/repos/{owner}/{repo}/issues/{index}/times`
- [ ] GET `/repos/{owner}/{repo}/issues/{index}/times`
- [ ] POST `/repos/{owner}/{repo}/issues/{index}/times`
- [ ] DELETE `/repos/{owner}/{repo}/issues/{index}/times/{id}`

## Organizations

- [ ] POST `/org/{org}/repos`
- [ ] GET `/orgs`
- [x] POST `/orgs`
- [x] DELETE `/orgs/{org}`
- [x] GET `/orgs/{org}`
- [x] PATCH `/orgs/{org}`
- [ ] GET `/orgs/{org}/actions/runners/registration-token`
- [ ] GET `/orgs/{org}/actions/secrets`
- [ ] DELETE `/orgs/{org}/actions/secrets/{secretname}`
- [ ] PUT `/orgs/{org}/actions/secrets/{secretname}`
- [ ] GET `/orgs/{org}/actions/variables`
- [ ] DELETE `/orgs/{org}/actions/variables/{variablename}`
- [ ] GET `/orgs/{org}/actions/variables/{variablename}`
- [ ] POST `/orgs/{org}/actions/variables/{variablename}`
- [ ] PUT `/orgs/{org}/actions/variables/{variablename}`
- [ ] GET `/orgs/{org}/activities/feeds`
- [ ] DELETE `/orgs/{org}/avatar`
- [ ] POST `/orgs/{org}/avatar`
- [ ] GET `/orgs/{org}/blocks`
- [ ] DELETE `/orgs/{org}/blocks/{username}`
- [ ] GET `/orgs/{org}/blocks/{username}`
- [ ] PUT `/orgs/{org}/blocks/{username}`
- [ ] GET `/orgs/{org}/hooks`
- [ ] POST `/orgs/{org}/hooks`
- [ ] DELETE `/orgs/{org}/hooks/{id}`
- [ ] GET `/orgs/{org}/hooks/{id}`
- [ ] PATCH `/orgs/{org}/hooks/{id}`
- [ ] GET `/orgs/{org}/labels`
- [ ] POST `/orgs/{org}/labels`
- [ ] DELETE `/orgs/{org}/labels/{id}`
- [ ] GET `/orgs/{org}/labels/{id}`
- [ ] PATCH `/orgs/{org}/labels/{id}`
- [x] GET `/orgs/{org}/members`
- [x] DELETE `/orgs/{org}/members/{username}`
- [x] GET `/orgs/{org}/members/{username}`
- [x] GET `/orgs/{org}/public_members`
- [x] DELETE `/orgs/{org}/public_members/{username}`
- [x] GET `/orgs/{org}/public_members/{username}`
- [x] PUT `/orgs/{org}/public_members/{username}`
- [x] GET `/orgs/{org}/repos`
- [x] POST `/orgs/{org}/repos`
- [ ] GET `/orgs/{org}/teams`
- [ ] POST `/orgs/{org}/teams`

## Notifications

- [ ] GET `/notifications`
- [ ] PUT `/notifications`
- [ ] GET `/notifications/new`
- [ ] GET `/notifications/threads/{id}`
- [ ] PATCH `/notifications/threads/{id}`

## ActivityPub

- [ ] GET `/activitypub/user-id/{user-id}`
- [ ] POST `/activitypub/user-id/{user-id}/inbox`

## Admin

- [ ] GET `/admin/cron`
- [ ] POST `/admin/cron/{task}`
- [ ] GET `/admin/emails`
- [ ] GET `/admin/hooks`
- [ ] POST `/admin/hooks`
- [ ] DELETE `/admin/hooks/{id}`
- [ ] GET `/admin/hooks/{id}`
- [ ] PATCH `/admin/hooks/{id}`
- [ ] GET `/admin/orgs`
- [ ] GET `/admin/runners/registration-token`
- [ ] GET `/admin/unadopted`
- [ ] DELETE `/admin/unadopted/{owner}/{repo}`
- [ ] POST `/admin/unadopted/{owner}/{repo}`
- [ ] GET `/admin/users`
- [ ] POST `/admin/users`
- [ ] DELETE `/admin/users/{username}`
- [ ] PATCH `/admin/users/{username}`
- [ ] DELETE `/admin/users/{username}/badges`
- [ ] GET `/admin/users/{username}/badges`
- [ ] POST `/admin/users/{username}/badges`
- [ ] POST `/admin/users/{username}/keys`
- [ ] DELETE `/admin/users/{username}/keys/{id}`
- [ ] POST `/admin/users/{username}/orgs`
- [ ] POST `/admin/users/{username}/rename`
- [ ] POST `/admin/users/{username}/repos`

## Packages

- [ ] GET `/packages/{owner}`
- [ ] DELETE `/packages/{owner}/{type}/{name}/{version}`
- [ ] GET `/packages/{owner}/{type}/{name}/{version}`
- [ ] GET `/packages/{owner}/{type}/{name}/{version}/files`

## Settings

- [ ] GET `/settings/api`
- [ ] GET `/settings/attachment`
- [ ] GET `/settings/repository`
- [ ] GET `/settings/ui`

## Teams

- [ ] DELETE `/teams/{id}`
- [ ] GET `/teams/{id}`
- [ ] PATCH `/teams/{id}`
- [ ] GET `/teams/{id}/activities/feeds`
- [ ] GET `/teams/{id}/members`
- [ ] DELETE `/teams/{id}/members/{username}`
- [ ] GET `/teams/{id}/members/{username}`
- [ ] PUT `/teams/{id}/members/{username}`
- [ ] GET `/teams/{id}/repos`
- [ ] DELETE `/teams/{id}/repos/{org}/{repo}`
- [ ] GET `/teams/{id}/repos/{org}/{repo}`
- [ ] PUT `/teams/{id}/repos/{org}/{repo}`

## Miscellaneous

- [ ] GET `/version`
- [ ] GET `/gitignore/templates`
- [ ] GET `/gitignore/templates/{name}`
- [ ] GET `/label/templates`
- [ ] GET `/label/templates/{name}`
- [ ] GET `/licenses`
- [ ] GET `/licenses/{name}`
- [ ] POST `/markdown`
- [ ] POST `/markdown/raw`
- [ ] POST `/markup`
- [ ] GET `/nodeinfo`
- [ ] GET `/signing-key.gpg`
